//Staticroute-All the view related routes are handel by this route like render home page,login,signup
const express=require('express');
const router=express.Router();
const URL=require('../Models/URL');
const {fetchUser, restrictUser}=require('../Middleware/auth')

//router:dsiplays all url generated by the user
router.get('/',fetchUser,restrictUser(["Admin","Normal"]),fetchUser,async(req,res)=>{
    console.log(req.user.id);
    const allurls=await URL.find({User:req.user.id});
    return res.render('Home',{
        urls:allurls
    });
});

//router:dsiplays all url generated by all the user-->Only admin can access this route
router.get('/admin',fetchUser,restrictUser(["Admin"]),async(req,res)=>{
    console.log(req.user.id);
    const allurls=await URL.find({});
    return res.render('Home',{
        urls:allurls
    });
})
router.get('/signup',async(req,res)=>{
    return res.render("Signup");
})
router.get('/login',async(req,res)=>{
    return res.render("Login");
})
module.exports=router;